### ISSUE TITLE
[Investigate] Improve memory usage when having `InfrastructureLocationProfileCostReport`

### ISSUE THREAD

**Issue by Carsopre** [Deltares/Koswat#168]
During PR #167 it was seen that when running a `KoswatSummary` that generates a collection of `InfrastructureLocationProfileCostReport` it is virtually impossible to go through the breakpoints as VSCode tries to retrieve in memory all those instances.

Ironically this does not happen when simply "running" a test, as can be shown by running the tests either locally or via TeamCity.

**Note:** this issue should not be picked prior to the extensions of the "Strategies" so that infrastructure costs are also considered as potentially said implementation might affect the current handling of the `list[InfrastructureLocationProfileCostReport]` for `KoswatSummary`.

**What needs to be done?**
- Find a potential solution that does not affect the running time of the current cases.
- Write this design decision in the related `README.md` or / and the official Koswat documentation.

**Acceptance criteria**
- The root problem is identified and properly documented.
- In case a solution has been found, it is discussed with the team and PO and implemented IF worth time-wise.
- The solution is documented.

**Comment by ArdtK** [comment]
![Image](https://github.com/user-attachments/assets/6fb6a35e-a2da-4ccb-8d10-6a83dbd47312)

**Comment by ArdtK** [comment]
Root cause is the `list[PointSurroundings]` that is part of `SurroundingsInfrastructure`.
