### ISSUE TITLE
Adjust calculation wall length for stability screen and cofferdam

### ISSUE THREAD

**Issue by ArdtK** [Deltares/Koswat#180]
Links to #181 
@peterdgr add calculations

**Comment by peterdgr** [comment]
The length of the stability and cofferdam construction is also dependent on the required piping length. 

In the calculation a total construction length of 0 is returned when there is no required piping length (if soil_binnen_berm_breedte == 0).  This is not correct, still a wall length for stability needs to be calculated. See changes in attached files.

[stability_wall_and_cofferdam_input_profile_calculation.zip](https://github.com/user-attachments/files/17472834/stability_wall_and_cofferdam_input_profile_calculation.zip)
