### ISSUE TITLE
Extend calculations for having berm as part of input profile

### ISSUE THREAD

**Issue by ArdtK** [Deltares/Koswat#181]

**Comment by peterdgr** [comment]
Within the different measures the innerslope, inner_berm_width and inner_berm_height are calculated based on the existing dike dimensions and the reinforcement scenario (dh, ds, dp). So far we didn't take the existing berm width into account in the calculations. When there is an existing berm, the question is whether this is meant for piping or macrostability. Depending on that the new dike dimensions should be determined. 

New logic needs to be defined and implemented --> @peterdgr 
Tests should be added, existing tests should not fail (profiles should still be the same)

**Comment by ArdtK** [comment]
Agreed:
- Keep branch open as research branch
- If it works functionally, merge master to branch (Peter/GAP)
- Then review/refactor branch and fix unittests (GAP)
